project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  title: "**Template-nf user guide**"
  navbar:
    background: primary
    # Top navigation bar with high-level sections
    right:
      - text: "Home"
        href: index.qmd
      - text: "Tutorial"
        href: notebooks/demo.qmd
      - text: "Components"
        href: notebooks/components.qmd
      - text: "How-to Guides"
        href: notebooks/how-to.qmd
      - text: "Best Practices"
        href: notebooks/best-practices.qmd
      - text: "Resources"
        href: notebooks/resources.qmd
    search: true
  sidebar:
    style: "floating"
    logo: "figs/SIH_logo.png"
    search: true
    collapse-level: 1
    contents:
      - text: "Tutorial"
        href: notebooks/demo.qmd
      - text: "How-to Guides"
        href: notebooks/how-to.qmd
      - section: "Template Components"
        href: notebooks/components.qmd 
        contents:
          - notebooks/main-nf.qmd
          - notebooks/nextflow-config.qmd
          - notebooks/modules.qmd
          - notebooks/bin.qmd
          - notebooks/configs.qmd
          - notebooks/bits.qmd
      - section: "Best Practices"
        href: notebooks/best-practices.qmd
        contents:
          - notebooks/channels.qmd
          - notebooks/resource-config.qmd
          - notebooks/software.qmd

format:
  html:
    theme: simplex
    css: styles.scss
    toc: false              
    toc-location: left     
    toc-depth: 2            
    code-overflow: wrap
    code-link: true
    code-fold: false
    highlight-style: github
    #page-layout: full
