project:
  type: website
  output-dir: docs

website:
  title: "**Template-nf user guide**"
  navbar:
    background: primary
    # Top navigation bar with high-level sections
    right:
      - text: "Home"
        href: index.qmd
      - text: "Components"
        href: notebooks/components.qmd
      - text: "How-to Guides"
        href: notebooks/how-to.qmd
      - text: "Best Practices"
        href: notebooks/best-practices.qmd
      - text: "Resources"
        href: notebooks/resources.qmd
    search: true
  sidebar:
    style: "floating"
    logo: "figs/SIH_logo.png"
    search: true
    collapse-level: 1
    contents:
      - section: "Tutorial"
        href: notebooks/tutorial.qmd
        contents:
          - notebooks/demo.qmd
        collapse: true   # Ensures subsections are collapsed by default
      - section: "How-to Guides"
        href: notebooks/how-to.qmd
        contents:
          - notebooks/template.qmd
        collapse: true   # Ensures subsections are collapsed by default
      - section: "Template Components"
        href: notebooks/components.qmd 
        contents:
          - notebooks/main-nf.qmd
          - notebooks/nextflow-config.qmd
          - notebooks/modules.qmd
          - notebooks/bin.qmd
          - notebooks/configs.qmd
          - notebooks/bits.qmd
        collapse: true   # Ensures subsections are collapsed by default
      - section: "Best Practices"
        href: notebooks/best-practices.qmd
        contents:
          - notebooks/resource-config.qmd
          - notebooks/software.qmd
        collapse: true   # Ensures subsections are collapsed by default

format:
  html:
    theme: simplex
    css: styles.scss
    toc: false              # Enable TOC globally for all pages
    toc-location: left      # Ensure TOC appears on the sidebar
    toc-depth: 2            # Set the depth of TOC (adjust as necessary)
    code-overflow: wrap
    code-link: true
    code-fold: false
    highlight-style: github
