project:
  type: website
  output-dir: docs

website:
  title: "Nextflow DSL2 template user guide"
  sidebar:
    style: "floating"
    search: true
    contents: 
      - index.qmd
      - template.qmd
      - section: "**Template components**"
        contents:
          - notebooks/main-nf.qmd
          - notebooks/nextflow-config.qmd
          - notebooks/modules.qmd
          - notebooks/bin.qmd
          - notebooks/configs.qmd
      - notebooks/configuration.qmd
      - notebooks/software.qmd
      - notebooks/hands-on.qmd
      - notebooks/guides.qmd
      - resources.qmd
  body-footer: "<div style='font-size: 14px;'>All materials copyright Sydney Informatics Hub, University of Sydney</div>"


format:
  html:
   toc: false
   theme:
      light: flatly
      dark: darkly
   css: styles.scss
   code-link: true
   code-fold: false
   code-overflow: scroll
   highlight-style: github
   page-layout: full


